/* 5.21: observable save results, connection evidence and per-user view preferences. */
(function(){
 'use strict';const app=window.app;if(!app||app.__operationsUX)return;app.__operationsUX=true;
 const hook=(name,after)=>{const old=app[name];if(typeof old!=='function')return;app[name]=function(...args){const r=old.apply(this,args);after.apply(this,args);return r;};};
 const regions=[];
 ['screen-user','screen-admin','screen-supervisor'].forEach(id=>{const screen=document.getElementById(id);const header=screen?.querySelector('header');if(!header)return;const n=document.createElement('div');n.className='ops-health';n.innerHTML='<span class="ops-network"></span><span class="ops-save" role="status" aria-live="polite"></span>';header.append(n);regions.push(n);});
 const streams={items:'สินค้า',topup:'เติมสินค้า',move:'ย้าย',history:'ประวัติ'};
 let pending=0,failed=false,saveLabel='';
 function paint(){const h=app._dataHealth||{},offline=navigator.onLine===false,values=Object.values(streams);const entries=Object.keys(streams).map(k=>h[k]);const all=entries.every(e=>e?.state==='server');const error=entries.some(e=>e?.state==='error');const dates=entries.filter(Boolean).map(e=>e.lastServer).filter(Boolean);const oldest=dates.length===values.length?Math.min(...dates):null;
  let label=offline?'ออฟไลน์ · ข้อมูลอาจไม่ล่าสุด':error?'เชื่อมต่อข้อมูลบางส่วนไม่สำเร็จ':all?'ข้อมูลหลักได้รับจากเซิร์ฟเวอร์แล้ว':'กำลังรอข้อมูลจากเซิร์ฟเวอร์';
  if(all&&oldest)label+=' · '+new Date(oldest).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'});
  regions.forEach(n=>{const net=n.querySelector('.ops-network');net.textContent=label;net.dataset.state=offline||error?'error':all?'ready':'waiting';net.title=Object.keys(streams).map(k=>{const e=h[k];return streams[k]+': '+(!e?'ยังไม่ได้รับ':e.state==='server'?'จากเซิร์ฟเวอร์':e.state==='error'?'เชื่อมต่อไม่สำเร็จ':'ข้อมูลในเครื่อง')+(e?.lastServer?' · '+new Date(e.lastServer).toLocaleString('th-TH'):'');}).join('\n');const s=n.querySelector('.ops-save');s.textContent=pending?'กำลังบันทึก '+pending+' ชุด'+(offline?' · รอเชื่อมต่อ':''):saveLabel;s.dataset.state=pending?'saving':failed?'error':'saved';});
 }
 app.refreshOperationsStatus=paint;
 ['saveToFirebase','saveManyToFirebase','commitWorkflowDocuments'].forEach(name=>{const old=app[name];if(typeof old!=='function')return;app[name]=async function(...args){if(!pending)failed=false;pending++;paint();let result;try{result=await old.apply(this,args);if(result!==true){failed=true;saveLabel=result==='already'?'รายการถูกดำเนินการแล้ว กรุณาตรวจข้อมูลล่าสุด':'บันทึกไม่สำเร็จ กรุณาตรวจรายการและลองใหม่';}return result;}catch(e){failed=true;saveLabel='บันทึกไม่สำเร็จ กรุณาตรวจรายการและลองใหม่';throw e;}finally{pending--;if(!pending&&!failed)saveLabel='บันทึกล่าสุดสำเร็จ';paint();}};});
 const actionAliases={performSave:['save'],confirmFinishJob:[],performConfirmMove:[],confirmBulkReceive:[],confirmReceivingWritten:[],adminConfirmMove:[],confirmImport:[],submitIssue:[],acceptJob:[]};
 Object.entries(actionAliases).forEach(([name,aliases])=>{const old=app[name];if(typeof old!=='function')return;let busy=false;app[name]=async function(...args){if(busy)return false;busy=true;const names=[name,...aliases];const buttons=[...document.querySelectorAll('button[onclick]')].filter(b=>names.some(n=>b.getAttribute('onclick').includes('.'+n+'(')));const states=buttons.map(b=>[b,b.disabled,b.getAttribute('aria-busy')]);buttons.forEach(b=>{b.disabled=true;b.setAttribute('aria-busy','true');b.classList.add('ops-saving');});try{return await old.apply(this,args);}finally{busy=false;states.forEach(([b,disabled,aria])=>{b.disabled=disabled;b.classList.remove('ops-saving');if(aria===null)b.removeAttribute('aria-busy');else b.setAttribute('aria-busy',aria);});}};});
 window.addEventListener('plas-data-health',paint);window.addEventListener('offline',paint);window.addEventListener('online',()=>{Object.values(app._dataHealth||{}).forEach(e=>e.state='cache');paint();});
 let preferenceUser='',restoring=false;
 const validReceiving=['unwritten','ready','noloc','waiting','written','all'];
 function key(){return preferenceUser?'plas-view-v1:'+encodeURIComponent(preferenceUser):null;}
 function snapshot(){return {query:document.getElementById('inp-search')?.value||'',chips:app.state.ui.searchChips||[],exclude:!!app._searchExcludeMode,receiving:app._receivingFilter||'unwritten',history:app.state.filters.historyFilter||'all',historyView:app._historyView||'time',historyQuery:document.getElementById('ws-history-search')?.value||'',monitor:app.state.filters.monitorFilter||'active'};}
 function persist(){if(restoring||!key())return;try{localStorage.setItem(key(),JSON.stringify(snapshot()));}catch(e){/* Device storage can be disabled; never block work. */}}
 function restore(){let p={};try{p=JSON.parse(localStorage.getItem(key())||'{}')||{};}catch(e){}restoring=true;try{clearTimeout(app.state.searchDebounceTimer);app.state.ui.searchChips=Array.isArray(p.chips)?p.chips.filter(c=>c&&typeof c.term==='string').slice(0,60).map(c=>({term:c.term.slice(0,300),exclude:!!c.exclude})):[];app._searchExcludeMode=!!p.exclude;app._receivingFilter=validReceiving.includes(p.receiving)?p.receiving:'unwritten';app.state.filters.historyFilter=['all','receive','topup','move','rejected'].includes(p.history)?p.history:'all';app.state.filters.monitorFilter=['active','done'].includes(p.monitor)?p.monitor:'active';app._historyView=p.historyView==='person'?'person':'time';const query=typeof p.query==='string'?p.query.slice(0,500):'';const field=document.getElementById('inp-search');if(field)field.value=query;app.state.filters.search=app.buildSearchQuery(query);app.renderSearchChips();app.updateSearchHint(app.state.filters.search);document.getElementById('search-mode-include')?.classList.toggle('is-active',!p.exclude);document.getElementById('search-mode-exclude')?.classList.toggle('is-active',!!p.exclude);const history=document.getElementById('ws-history-search');if(history){history.value=typeof p.historyQuery==='string'?p.historyQuery.slice(0,500):'';history.dispatchEvent(new Event('input',{bubbles:true}));}app._receivingSelected={};app.refreshCurrentView();}finally{restoring=false;}}
 app.saveViewPreferences=persist;app.restoreViewPreferences=restore;
 app.resetViewPreferences=function(){if(key())try{localStorage.removeItem(key());}catch(e){}restore();persist();app.toast('คืนตัวกรองเริ่มต้นแล้ว','info');};
 const login=app.login;app.login=function(user){persist();const who=user==='Supervisor'?'Supervisor:'+String(this._svPersonName||''):String(user||'');const result=login.apply(this,arguments);if(this.state.ui.currentUser===user){preferenceUser=who;restore();}return result;};
 const logout=app.logout;app.logout=function(){persist();preferenceUser='';return logout.apply(this,arguments);};
 ['handleSearch','setSearchMode','commitSearchChip','removeSearchChip','clearSearch','setReceivingFilter','filterHistory','setHistoryView','filterMonitor'].forEach(n=>hook(n,persist));
 document.getElementById('ws-history-search')?.addEventListener('input',persist);
 const search=document.getElementById('search-container');if(search){const b=document.createElement('button');b.type='button';b.className='ops-reset-filters';b.textContent='คืนตัวกรองเริ่มต้น';b.addEventListener('click',()=>app.resetViewPreferences());search.append(b);}
 regions.filter(n=>!n.closest('#screen-user')).forEach(n=>{const b=document.createElement('button');b.type='button';b.className='ops-reset-filters';b.textContent='คืนตัวกรองเริ่มต้น';b.addEventListener('click',()=>app.resetViewPreferences());n.append(b);});
 if(app.state.ui.currentUser){preferenceUser=String(app.state.ui.currentUser);restore();}
 const viewport=window.visualViewport;
 function fit(){const detail=document.getElementById('modal-detail');const editing=!!document.activeElement?.closest('#modal-detail')&&/INPUT|TEXTAREA/.test(document.activeElement.tagName);const small=window.innerWidth<768;document.body.classList.toggle('ops-keyboard',small&&editing);if(viewport){document.documentElement.style.setProperty('--ops-vh',viewport.height+'px');document.documentElement.style.setProperty('--ops-vtop',viewport.offsetTop+'px');}if(small&&editing&&detail&&!detail.classList.contains('hidden'))document.activeElement.scrollIntoView({block:'nearest'});}
 viewport?.addEventListener('resize',fit);viewport?.addEventListener('scroll',fit);document.addEventListener('focusin',fit);document.addEventListener('focusout',()=>setTimeout(fit,0));
 paint();
})();
