/* PLAS 5.16 — screen composition; existing data/authorization handlers own writes. */
(function(){
 'use strict';
 const app=window.app;if(!app||app.__workspacePages)return;app.__workspacePages=true;
 const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const node=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n;};
 const hook=(name,after)=>{const old=app[name];if(typeof old==='function')app[name]=function(...args){const result=old.apply(this,args);after.apply(this,args);return result;};};
 const meta=h=>h.action==='TopUp'?['เติมสินค้า','arrow-fat-line-up','mint']:h.action==='Move'?['ย้ายสินค้า','arrows-left-right','lilac']:h.action==='Rejected'?['ยกเลิกสินค้า','prohibit','rose']:[h.action==='write'?'เขียน Location':h.action==='done'?'รับสินค้าแล้ว':'รับเข้า','arrow-fat-line-down','blue'];
 function timeOf(h){const value=h.timestamp&&h.timestamp.toMillis?h.timestamp.toMillis():h.timestamp||h.id;const d=new Date(Number(value));return Number.isFinite(d.getTime())&&d.getFullYear()>2000?d:null;}
 function dayOf(h){const d=timeOf(h);return d?d.toLocaleDateString('th-TH',{day:'numeric',month:'short',year:'numeric'}):h.date||'ไม่ระบุวันที่';}
 function historyRow(h){const m=meta(h);return '<article class="ws-history-row"><span class="ws-action-icon '+m[2]+'"><i class="ph ph-'+m[1]+'" aria-hidden="true"></i></span><div class="ws-history-item"><strong>'+esc(h.item||h.code||'-')+'</strong><span>'+esc(h.user||'ไม่ระบุผู้ทำรายการ')+' · '+m[0]+'</span></div><div class="ws-history-qty"><b>'+esc(h.qty==null?'-':h.qty)+'</b><small>จำนวน</small></div><div class="ws-history-loc"><b>'+esc(h.loc||'-')+'</b><time>'+esc(h.time||(timeOf(h)?timeOf(h).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'}):'-'))+'</time></div>'+((h.remark||h.rejectReason||h.resolution)?'<div class="ws-history-note">'+esc(h.resolution||h.rejectReason||h.remark)+'</div>':'')+'</article>';}
 let histQuery='',histLimit=60;
 const history=d=>document.getElementById(d);
 function prepareHistory(){const view=history('view-history');if(!view||history('ws-history-header'))return;
  const header=node('header','ws-page-head');header.id='ws-history-header';header.innerHTML='<div><span class="ws-eyebrow">ACTIVITY</span><h2>ประวัติการทำงาน</h2><p>รายการที่บันทึกไว้ในระบบ</p></div><span class="ws-head-icon lilac"><i class="ph ph-clock-counter-clockwise" aria-hidden="true"></i></span>';view.prepend(header);
  const controls=node('div','ws-history-tools');controls.innerHTML='<label class="ws-search"><i class="ph ph-magnifying-glass" aria-hidden="true"></i><input type="search" id="ws-history-search" placeholder="ค้นหา Item / Location / ผู้ทำรายการ" aria-label="ค้นหาประวัติ"></label><div class="ws-view-switch" role="group" aria-label="รูปแบบประวัติ"><button type="button" data-history-view="time">ตามเวลา</button><button type="button" data-history-view="person">ตามคน</button></div>';
  history('history-list-content').before(controls);
  let debounce;controls.querySelector('input').addEventListener('input',e=>{histQuery=e.target.value;histLimit=60;clearTimeout(debounce);debounce=setTimeout(()=>app.renderHistory(),100);});
  controls.querySelectorAll('[data-history-view]').forEach(b=>b.addEventListener('click',()=>{histLimit=60;app.setHistoryView(b.dataset.historyView);}));
 }
 app.renderHistory=function(){prepareHistory();const container=history('history-list-content');if(!container)return;
  const filter=this.state.filters.historyFilter||'all';let list=[...(this.state.data.history||[])].filter(h=>filter==='all'||filter==='receive'&&!['TopUp','Move','Rejected'].includes(h.action)||filter==='topup'&&h.action==='TopUp'||filter==='move'&&h.action==='Move'||filter==='rejected'&&h.action==='Rejected');
  const q=histQuery.trim().toLocaleLowerCase();if(q)list=list.filter(h=>[h.item,h.code,h.comp,h.loc,h.user,h.action,h.remark,h.rejectReason,h.resolution].some(v=>String(v||'').toLocaleLowerCase().includes(q)));
  list.sort((a,b)=>(timeOf(b)?.getTime()||0)-(timeOf(a)?.getTime()||0));
  const mode=this._historyView||'time';document.querySelectorAll('[data-history-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.historyView===mode)));
  const total=list.reduce((sum,h)=>sum+(Number.isFinite(Number(h.qty))?Number(h.qty):0),0);
  let html='<div class="ws-history-summary"><span><b>'+list.length+'</b> รายการ</span><span><b>'+new Set(list.map(h=>h.user)).size+'</b> คน</span><span><b>'+total.toLocaleString('th-TH',{maximumFractionDigits:6})+'</b> จำนวนรวม</span></div>';
  if(!list.length){container.innerHTML=html+'<div class="ws-empty"><i class="ph ph-clock" aria-hidden="true"></i><h3>'+(q?'ไม่พบประวัติที่ตรงกัน':'ยังไม่มีประวัติในหมวดนี้')+'</h3><p>'+(q?'ลองใช้เลข Item, Location หรือชื่อผู้ทำรายการ':'รายการจะปรากฏเมื่อมีการบันทึกงาน')+'</p></div>';return;}
  const groups=new Map();list.slice(0,histLimit).forEach(h=>{const k=mode==='person'?h.user||'ไม่ระบุชื่อ':dayOf(h);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(h);});
  groups.forEach((rows,key)=>{html+='<section class="ws-history-group"><h3>'+esc(key)+'<span>'+rows.length+' รายการ</span></h3><div>'+rows.map(historyRow).join('')+'</div></section>';});
  if(list.length>histLimit)html+='<button type="button" class="ws-more">แสดงเพิ่ม · เหลือ '+(list.length-histLimit)+' รายการ</button>';
  container.innerHTML=html;container.querySelector('.ws-more')?.addEventListener('click',()=>{histLimit+=60;app.renderHistory();});
 };
 function decorateIssues(){const view=document.getElementById('view-issues');if(!view)return;const count=view.querySelectorAll('.item-enter').length;const header=node('header','ws-page-head ws-grid-head');header.innerHTML='<div><span class="ws-eyebrow">NEEDS ATTENTION</span><h2>รายการที่ต้องตรวจสอบ <span class="ws-count">'+count+'</span></h2><p>เปิดรายการเพื่อดูรายละเอียดและดำเนินการต่อ</p></div><span class="ws-head-icon peach"><i class="ph ph-warning-circle" aria-hidden="true"></i></span>';view.prepend(header);
  const items=app.getIssueItems();view.querySelectorAll('.item-enter').forEach(card=>{const item=items.find(i=>String(i.comp||'')===card.dataset.plasComp&&String(i.code||'')===card.dataset.plasCode&&card.getAttribute('onclick')==='window.app.openModal('+i.id+')');if(!item)return;const note=node('div','ws-issue-note');note.append(node('strong','',item.issueType||item.issueNote||'รอตรวจสอบปัญหา'));if(item.issueDescription)note.append(node('p','',item.issueDescription));if(item.issueReportedBy||item.issueReportedDate)note.append(node('small','',[item.issueReportedBy,item.issueReportedDate].filter(Boolean).join(' · ')));if(item.resolution||item.issueResolution)note.append(node('p','ops-resolution','ผลดำเนินการ: '+(item.resolution||item.issueResolution)+(item.resolvedBy?' · '+item.resolvedBy:'')));card.append(note);card.setAttribute('role','button');card.tabIndex=0;card.setAttribute('aria-label','เปิดปัญหา '+item.code);card.addEventListener('keydown',e=>{if(e.target===card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();app.openModal(item.id);}});});
 }
 hook('renderIssues',decorateIssues);
 function decorateIssueForm(){const modal=document.getElementById('modal-issue');if(!modal)return;modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-label','แจ้งปัญหาสินค้า');
  let context=modal.querySelector('.ws-issue-context');if(!context){context=node('div','ws-issue-context');modal.querySelector('h3').parentElement.after(context);}const item=app.state.current.item||{};context.innerHTML='<span>สินค้าที่กำลังแจ้งปัญหา</span><b>'+esc(item.code||'-')+'</b><small>'+esc(item.comp||'')+'</small>';
  modal.querySelectorAll('button[onclick*="selectIssueType"]').forEach(b=>{b.classList.add('ws-issue-choice');b.setAttribute('aria-pressed',String(b.getAttribute('onclick').includes("'"+app.state.current.issueType+"'")));});
  modal.querySelector('button[onclick*="closeIssueModal"]').setAttribute('aria-label','ปิดหน้าระบุปัญหา');
 }
 hook('openIssueModal',decorateIssueForm);hook('selectIssueType',decorateIssueForm);
 const oldProfile=app.openProfileSettings;
 if(oldProfile)app.openProfileSettings=function(username){this.closeProfileSettings();oldProfile.call(this,username);const modal=document.getElementById('modal-profile-settings');if(!modal)return;modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-label','โปรไฟล์ '+username);
  const shell=modal.firstElementChild;shell.classList.add('ws-profile-shell');const children=[...shell.children];const head=children[0],portrait=children[1],controls=children[2];head.classList.add('ws-profile-head');head.querySelector('button').setAttribute('aria-label','ปิดโปรไฟล์');portrait.classList.add('ws-profile-portrait');controls.classList.add('ws-profile-controls');
  const layout=node('div','ws-profile-layout');layout.append(portrait,controls);shell.append(layout);const caption=node('p','ws-profile-caption','รูปโปรไฟล์นี้ใช้ในการเลือกผู้ใช้งาน');portrait.append(caption);const upload=portrait.querySelector('label');if(upload)upload.setAttribute('aria-label','เปลี่ยนรูปโปรไฟล์');const toggle=controls.querySelector('#pin-enabled-toggle');if(toggle)toggle.setAttribute('aria-label','ใช้รหัส PIN');
  const footer=node('footer','ws-profile-foot');const close=node('button','ws-primary','เสร็จสิ้น');close.type='button';close.addEventListener('click',()=>this.closeProfileSettings());footer.append(close);shell.append(footer);
 };
 hook('openSettings',function(){const modal=document.getElementById('modal-settings');modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-label','ตั้งค่าระบบ');modal.querySelector('.set-nav').setAttribute('aria-label','หมวดการตั้งค่า');modal.querySelectorAll('.set-mobile-head').forEach(el=>{el.setAttribute('role','button');el.tabIndex=0;if(!el.dataset.wsKeys){el.dataset.wsKeys='1';el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();el.click();}});}});});
 const nativeEmpty=app.emptyState;
 app.emptyState=function(title,sub){const translated=title==='No items'?'ไม่มีรายการ':title==='No history'?'ยังไม่มีประวัติ':title;return '<div class="ws-empty"><span class="ws-empty-art"><i class="ph ph-package" aria-hidden="true"></i></span><h3>'+esc(translated)+'</h3><p>'+esc(sub)+'</p></div>';};
 let scannerReturn=null;
 app.openLocationEntry=function(){const input=document.getElementById('inp-new-loc');if(!input||input.disabled)return;this.closeLocationEntry();scannerReturn=document.activeElement;
  const modal=node('div','ws-entry-overlay');modal.id='ws-location-entry';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-labelledby','ws-entry-title');
  modal.innerHTML='<section class="ws-entry-panel"><header><div><span class="ws-eyebrow">LOCATION</span><h2 id="ws-entry-title">สแกนหรือพิมพ์ตำแหน่ง</h2></div><button type="button" class="ws-entry-close" aria-label="ปิด"><i class="ph ph-x"></i></button></header><div class="ws-scan-frame"><i class="ph ph-barcode" aria-hidden="true"></i><p>ใช้เครื่องสแกน หรือกรอก Location ด้านล่าง</p></div><label for="ws-entry-input">Location ใหม่</label><input id="ws-entry-input" type="text" autocomplete="off" autocapitalize="characters" spellcheck="false" placeholder="เช่น LAU502-1"><p class="ws-entry-error" role="alert"></p><footer><button type="button" class="ws-entry-cancel">ยกเลิก</button><button type="button" class="ws-primary ws-entry-use">ใช้ Location นี้</button></footer></section>';
  document.body.append(modal);const field=modal.querySelector('input');field.value=input.value;
  const close=()=>this.closeLocationEntry();modal.querySelector('.ws-entry-close').onclick=close;modal.querySelector('.ws-entry-cancel').onclick=close;
  const submit=()=>{const value=field.value.trim().toUpperCase();if(!value){modal.querySelector('.ws-entry-error').textContent='กรุณาระบุ Location';return;}if(/^HTTPS?:\/\//i.test(value)){modal.querySelector('.ws-entry-error').textContent='กรุณาใช้รหัส Location โดยตรง';return;}input.value=value;input.dispatchEvent(new Event('input',{bubbles:true}));close();input.focus();};
  modal.querySelector('.ws-entry-use').onclick=submit;modal.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Tab'){const controls=[...modal.querySelectorAll('button,input')];const first=controls[0],last=controls[controls.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}if(e.key==='Enter'&&e.target===field){e.preventDefault();submit();}});field.focus();
 };
 app.closeLocationEntry=function(){const modal=document.getElementById('ws-location-entry');if(modal){modal.remove();scannerReturn?.focus();}};
 const loc=document.getElementById('inp-new-loc-container');if(loc){const button=node('button','ws-location-launch');button.type='button';button.innerHTML='<i class="ph ph-scan" aria-hidden="true"></i> สแกน / พิมพ์ Location';button.addEventListener('click',()=>app.openLocationEntry());loc.after(button);}
 prepareHistory();
})();
